### PR TITLE
fix(zod-openapi): support default response

### LINKED ISSUE #739: [zod-openapi] Default response support
OpenAPI supports describing response objects with status codes, status ranges, or using the `default` field (more in the [specification](https://swagger.io/specification/#responses-object)).

The `Default Response` section of `Describing Responses` documentation (see [here](https://swagger.io/docs/specification/describing-responses/#Default%20Response:~:text=each%20response%20individually.-,Default%20Response,-Sometimes%2C%20an%20operation)) states the following:

>  Sometimes, an operation can return multiple errors with different HTTP status codes, but all of them have the same response structure: 
> _(masked example section)_
>  You can use the `default` response to describe these errors collectively, not individually. **“Default” means this response is used for all HTTP codes that are not covered individually for this operation.**

This issue was first introduced in #519 with the support of status codes, which was later also extended in #535 to support the status ranges. It is now only missing the support for the default object.

---

Quick reproduction of an issue:
```typescript
import { createRoute, OpenAPIHono, z } from '@hono/zod-openapi';

export const app = new OpenAPIHono().openapi(
  createRoute({
    summary: 'Test route',
    method: 'post',
    path: '/test',
    responses: {
      200: {
        description: '',
        content: {
          'application/json': {
            schema: z.object({
              name: z.string(),
            }),
          },
        },
      },
      default: {
        description: '',
        content: {
          'application/json': {
            schema: z.object({
              result: z.number(),
            }),
          },
        },
      },
    },
  }),
  (c) => {
    return c.json(
      {
        result: 0
      },
      400
    );
  }
);
```

Typescript error for the example above:
```Argument of type '(c: Context<Env, "/test", {}>) => JSONRespondReturn<{ result: number; }, 400>' is not assignable to parameter of type 'Handler<Env, "/test", {}, MaybePromise<TypedResponse<any, 200, "json" | "text">>>'.
  Type 'JSONRespondReturn<{ result: number; }, 400>' is not assignable to type 'MaybePromise<TypedResponse<any, 200, "json" | "text">>'.
    Type 'JSONRespondReturn<{ result: number; }, 400>' is not assignable to type 'TypedResponse<any, 200, "json" | "text">'.
      Types of property '_status' are incompatible.
        Type '400' is not assignable to type '200'.ts(2345)
```

### PR DESCRIPTION
**Pull request by jstri**
Fixes #739

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @jstri 

Great! I love this PR. One thing. Can you run `yarn changeset` and push the changeset file?

**Comment by jstri** [comment]
Done. Thank you @yusukebe!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@jstri 

Thanks! I'll merge and release it!

**Pull request merged**
