### PR TITLE
fix(react-renderer): Change react-renderer props to interface

### PR DESCRIPTION
**Pull request by alexturpin**
Fixes honojs/honox#210

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @alexturpin 

Nice! One thing. Can you run `yarn changeset` on the top of the project to create a changeset and push it?

**Comment by alexturpin** [comment]
@yusukebe done, I think that looks right?

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@alexturpin Yes, great!  I'll merge now. Thanks!

**Pull request merged**
