### PR TITLE
Add Bun Transpiler middleware #344

### LINKED ISSUE #344: Bun TypeScript Transpiler Middleware
Analogous to the [`esbuild transpiler`](https://github.com/honojs/middleware/tree/main/packages/esbuild-transpiler) middleware that supports Node, Deno and Cloudflare, I propose the implementation of a `bun transpiler` middleware. I'd be happy to create a PR.

Example how it would be used:

```javascript
import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import { bunTranspiler } from '@hono/bun-transpiler'

const app = new Hono()

app.get('/static/:scriptName{.+.tsx?}', bunTranspiler())
app.get('/static/*', serveStatic({ root: './' }))

export default app
```

### PR DESCRIPTION
**Pull request by floriankapaun**
Closes #344

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @floriankapaun 

Cooool! I'd like to merge this, but there are some things that you want to do.

* Add CI into [here](https://github.com/honojs/middleware/tree/main/.github/workflows).
* Run `yarn build` to check if the build passes.
* Add a build command to [here](https://github.com/honojs/middleware/blob/965d5a3f6d1b1c7e2bd5d692c1ebeb6991fbc7dd/package.json#L11-L29).

Could you taka a look?

**Comment by floriankapaun** [comment]
Sure! I'll have a look.

**Comment by floriankapaun** [comment]
✅ done @yusukebe

**Comment by yusukebe** [comment]
@floriankapaun 

So quick! Looks good! Let's go!

**Pull request merged**
