### PR TITLE
feat: introduce brief middleware

### PR DESCRIPTION
**Pull request by pietrodev07**

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @pietrodev07 

Thank you for the PR.

Have you ever tried `showRoutes`?

https://hono.dev/docs/helpers/dev#showroutes

**Comment by pietrodev07** [comment]
> Hi @pietrodev07
> 
> Thank you for the PR.
> 
> Have you ever tried `showRoutes`?
> 
> https://hono.dev/docs/helpers/dev#showroutes

I discovered if after i've just opened this pr 🤣

**Comment by yusukebe** [comment]
> I discovered it after i've just opened this pr 🤣

Oh! Can I close this PR?

**Comment by yusukebe** [comment]
Closing. Thank you!

**Pull request closed without merging**
