### PR TITLE
fix(react-renderer): fix overwriting headers when stream is enabled

### PR DESCRIPTION
**Pull request by yoshikouki**
Correct the following issue

- https://github.com/honojs/middleware/issues/418

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @yoshikouki 

Looks good! One thing, can you add a test?

The problem is not only related to using Cookie Helper. It is caused by appending a header with the `append` option in a hander.

```ts
c.header('X-Message-Append', 'Hello', { append: true })
```

The same issue existed in JSX Renderer Middleware in Hono core. So, I've fixed that in https://github.com/honojs/hono/pull/2363, referring to your implementation.

You can write a test like the following:
https://github.com/honojs/hono/pull/2363/files#diff-d7b47b09589437bf3879179e25f6cb3283330a71424d01a0d9befc24af44fb41

**Comment by yoshikouki** [comment]
Absolutely! I'm more than happy to assist with that.

Thank you for providing the test case. I added it as a reference, but it resulted in an error.

```log
 RUN  v1.0.4 /Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer

stderr | test/react-renderer.test.tsx > Basic > Should return as streaming content with headers added in a handler
TypeError: renderToReadableStream is not a function
    at Context.renderer (/Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/src/react-renderer.ts:32:28)
    at dispatch (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/hono/dist/compose.js:29:17)
    at dispatch (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/hono/dist/compose.js:29:17)
    at file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/hono/dist/hono-base.js:247:25
    at /Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/test/react-renderer.test.tsx:116:17
    at runTest (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/@vitest/runner/dist/index.js:665:11)
    at runSuite (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/@vitest/runner/dist/index.js:782:15)
    at runSuite (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/@vitest/runner/dist/index.js:782:15)
    at runFiles (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/@vitest/runner/dist/index.js:831:5)
    at startTests (file:///Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/node_modules/@vitest/runner/dist/index.js:840:3)
```


## Error situation

I added debug comments like below, and found that `renderToReadableStream` exists in `bun test` but not in `yarn test`.

```ts
    if (options?.stream) {
      // const { renderToReadableStream } = await import('react-dom/server')
      const reactDomServer = await import('react-dom/server')
      console.log('reactDomServer:', reactDomServer)
      const { renderToReadableStream } = reactDomServer
```

https://github.com/honojs/middleware/blob/74dfa07dedb9b172c7434d4f564199d73aa75d94/packages/react-renderer/src/react-renderer.ts#L27-L28

### `yarn test`

```js
reactDomServer: [Module: null prototype] {
  default: {
    version: '18.2.0',
    renderToString: [Function: renderToString],
    renderToStaticMarkup: [Function: renderToStaticMarkup],
    renderToNodeStream: [Function: renderToNodeStream],
    renderToStaticNodeStream: [Function: renderToStaticNodeStream],
    renderToPipeableStream: [Function: renderToPipeableStream]
  },
  renderToNodeStream: [Function: renderToNodeStream],
  renderToPipeableStream: [Function: renderToPipeableStream],
  renderToStaticMarkup: [Function: renderToStaticMarkup],
  renderToStaticNodeStream: [Function: renderToStaticNodeStream],
  renderToString: [Function: renderToString],
  version: '18.2.0'
}
```

### `bun test`

```js
reactDomServer: Module {
  default: {
    version: "18.2.0",
    renderToString: [Function: renderToString],
    renderToStaticMarkup: [Function: renderToStaticMarkup],
    renderToNodeStream: [Function: renderToNodeStream],
    renderToStaticNodeStream: [Function: renderToStaticNodeStream],
    renderToReadableStream: [Function: renderToReadableStream],
  },
  renderToNodeStream: [Function: renderToNodeStream],
  renderToReadableStream: [Function: renderToReadableStream],
  renderToStaticMarkup: [Function: renderToStaticMarkup],
  renderToStaticNodeStream: [Function: renderToStaticNodeStream],
  renderToString: [Function: renderToString],
  version: "18.2.0",
}
```

## Why the error cause


Checking `react-dom/server`, there are 4 variants: node, browser, edge, and bun.

```json
    "./server": {
      "workerd": "./server.edge.js",
      "bun": "./server.bun.js",
      "deno": "./server.browser.js",
      "worker": "./server.browser.js",
      "browser": "./server.browser.js",
      "node": "./server.node.js",
      "edge-light": "./server.edge.js",
      "default": "./server.node.js"
    },
```
https://github.com/facebook/react/blob/1293047d6063f3508af15e68cca916660ded791e/packages/react-dom/package.json#L54-L63

Among these 4 variants, only node -- that is, `server.node.js` -- doesn't have `renderToReadableStream`.

- [`server.edge.js` has renderToReadableStream](https://github.com/facebook/react/blob/1293047d6063f3508af15e68cca916660ded791e/packages/react-dom/server.edge.js#L14-L19)
- [`server.browser.js` has renderToReadableStream](https://github.com/facebook/react/blob/1293047d6063f3508af15e68cca916660ded791e/packages/react-dom/server.browser.js#L39-L44)
- [`server.bun.js` has renderToReadableStream](https://github.com/facebook/react/blob/1293047d6063f3508af15e68cca916660ded791e/packages/react-dom/server.bun.js#L14-L19)

But [`server.node.js` doesn't have renderToReadableStream](https://github.com/facebook/react/blob/main/packages/react-dom/server.node.js)...😭

Considering the situation where it exists in `bun test` but not in `yarn test`, this seems to be the cause of the error.

---

## Possible solution

Although it's out of scope for this PR, to use Readable Stream in Node.js, we need to use either [renderToPipeableStream](https://react.dev/reference/react-dom/server/renderToPipeableStream) or [renderToStaticNodeStream](https://react.dev/reference/react-dom/server/renderToStaticNodeStream).


> ### Server APIs for Node.js Streams 
> These methods are only available in the environments with [Node.js Streams:](https://nodejs.org/api/stream.html)
> 
> - [renderToPipeableStream](https://react.dev/reference/react-dom/server/renderToPipeableStream) renders a React tree to a pipeable [Node.js Stream.](https://nodejs.org/api/stream.html)
> - [renderToStaticNodeStream](https://react.dev/reference/react-dom/server/renderToStaticNodeStream) renders a non-interactive React tree to a [Node.js Readable Stream.](https://nodejs.org/api/stream.html#readable-streams)

https://react.dev/reference/react-dom/server#server-apis-for-nodejs-streams

It seems that we can easily implement this by using [getRuntimeKey()](https://hono.dev/helpers/adapter#getruntimekey). 🤔

**Comment by yoshikouki** [comment]
# Results of test run with bun

```
❯ bun test test/react-renderer.test.tsx
bun test v1.0.30 (1424a196)

test/react-renderer.test.tsx:
122 |     expect(await res.text()).toBe('<h1>Hi</h1>')
123 |   })
124 | })
125 | 
126 | describe('Streaming', () => {
127 |   it.skip('Vitest does not support Streaming')
        ^
error: test.skip() expects a function
      at /Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/test/react-renderer.test.tsx:127:3
      at /Users/yoshikouki/src/github.com/yoshikouki/hono-middleware/packages/react-renderer/test/react-renderer.test.tsx:126:1
✓ Basic > Should return HTML with layout [4.70ms]
✓ Basic > Should return HTML without layout [0.53ms]
✓ Basic > Should return a default doctype [0.25ms]
✓ Basic > Should return a custom doctype [0.23ms]
✓ Basic > Should return as streaming content with headers added in a handler [3.63ms]

 5 pass
 0 fail
 18 expect() calls
Ran 5 tests across 1 files. [39.00ms]
```

**Comment by yusukebe** [comment]
Hey @yoshikouki 

Recently, the Cloudflare team released [@cloudflare/vitest-pool-workers](https://www.npmjs.com/package/@cloudflare/vitest-pool-workers). If we use it, we can test the functions using `renderToReadbleStream()` because the runtime will be `worked.` I've added the fix to support it: https://github.com/honojs/middleware/pull/422

So, you can test it if you merge the "main"!

**Comment by yoshikouki** [comment]
@yusukebe

Thank you for your response and the fix!!! 
Cloudflare team is truly amazing.

I rebased my branch against the main branch, and the tests are now passing. 👍

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Thanks @yoshikouki !

Merge now.

**Pull request merged**
