### PR TITLE
fix(zod-openapi): return type of handler should be MaybePromise

### LINKED ISSUE #521: [zod-openapi] Unable to use async handler
hono: 4.3.6
before @hono/zod-openapi: 0.11.1
after @hono/zod-openapi: 0.12.0

After updating from version 0.11.1 to version 0.12.0, I get a type error when using `async handler`.

```ts
const app = new OpenAPIHono()
  .openapi(createRoute({
    method: 'get',
    path: '/users',
    responses: {
      200: {
        description: 'users',
        content: {
          'application/json': {
            schema: z.array(
              z.object({
                id: z.string(),
                name: z.string(),
                age: z.number(),
              })
            ),
          },
        },
      },
    },
  }),
  async (c) => {
    const users = await getUsersQueryToDatabase()
    return c.json(users)
  })
```

This code is type error.

```
error TS2345: Argument of type '(c: Context<Env, "/users", {}>) => Promise<Response & TypedResponse<{ id: string; name: string; age: number; }[], 200, "json">>' is not assignable to parameter of type 'Handler<Env, "/projects", {}, TypedResponse<{ id: string; name: string; age: number; }[], 200, "json">>'.
  Type 'Promise<Response & TypedResponse<{ id: string; name: string; age: number; }[], 200, "json">>' is missing the following properties from type 'TypedResponse<{ id: string; name: string; age: number; }[], 200, "json">': data, status, format
```

No problem if the await result is not included in the response.

```ts
// no problem code
const app = new OpenAPIHono()
  .openapi(createRoute({
    method: 'delete',
    path: '/users/{id}',
    request: {
      params: z.object({ id: z.string() })
    },
    responses: {
      204: {
        description: 'success',
      },
    },
  }),
  async (c) => {
    const { id } = c.req.valid('param')
    await deleteUserQueryToDatabase(id)
    return c.json(null, 204)
  })
```

### PR DESCRIPTION
**Pull request by alexzhang1030**
closes #521

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @alexzhang1030 

Thank you for the quick fix! Could you see the CI error?

**Comment by alexzhang1030** [comment]
@yusukebe done! Looks like something is not lint well, I removed the duplicate things now.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@alexzhang1030 

Thanks! Merging now.

**Comment by akineko** [comment]
Thank you all.

**Pull request merged**
