### PR TITLE
feat(ajv-validator): Add Ajv validator middleware

### PR DESCRIPTION
**Pull request by ikhvost**
Hello,

I'd like to contribute an [Ajv](https://github.com/ajv-validator/ajv) validator middleware for Hono.

The implementation is primarily based on the existing Zod validator middleware, with minimal changes to accommodate Ajv's API. I've also included test cases similar to those used for the TypeBox and Zod validators.

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @ikhvost 

Thank you for the PR. I've left some coments. Check them out.

**Comment by ikhvost** [comment]
Hi, @yusukebe. I’ve incorporated all your suggestions; please review.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@ikhvost 

Thanks! I'll merge this now and release it.

**Pull request merged**
