### PR TITLE
fix(auth.js): clone request directly for bun

### PR DESCRIPTION
**Pull request by divyam234**
As bun now supports request cloning from  version 1.26 onwards  so workaround for cloning can be removed now @yusukebe. Ran test suite using bun its working fine. Also added popup login hook from example repo so that it can be imported directly from here.

### CODE REVIEW

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
> As bun now supports request cloning from version 1.26

Ah, I see! Thank you.

**Comment by 985563349** [comment]
@divyam234 @yusukebe 

I found that using the following cloning behavior will result in the inability to obtain c.req.json () in the future:

```typescript
const newReq = new Request(req)
const url = new URL(newReq.url)

// ...

return new Request(url.href, newReq)
```
I tried using the following code and was able to obtain it correctly:

```typescript
const url = new URL(req.url);
const newReq = new Request(url.href, req);

// ...

return new Request(url.href, newReq)
```

**Comment by 985563349** [comment]
If it's a bug, I want to submit a PR to fix it.😄

**Pull request merged**
