### PR TITLE
Allow passing state in google oath middleware

### PR DESCRIPTION
**Pull request by aaronware**
Minor adjustment to allow state to be a non required option while still falling back to the default random value if not provided

### CODE REVIEW

**Comment by yusukebe** [comment]
@aaronware Thanks!

@monoald Can you review this?

**Comment by monoald** [comment]
> @aaronware Thanks!
> 
> @monoald Can you review this?

@yusukebe 
It makes sense, state was expected but only default value was used. There is no need for state to be non-optional.

All good to go!

**Comment by monoald** [comment]
@aaronware Thanks!

Can you add the changeset?

**Comment by aaronware** [comment]
Yep, not a problem

**Comment by aaronware** [comment]
@monoald let me know if I didn't do it correctly. I've never done a changeset/changelog that way since our projects use release-please and it's automated. Seemed straightforward enough but wanted to confirm

**Comment by monoald** [comment]
@aaronware All good!

@yusukebe Ready to go!

**Comment by aaronware** [comment]
@yusukebe don't merge this just yet. I found a bug in my changes when retesting locally

**Comment by yusukebe** [comment]
@aaronware Okay!

**Comment by aaronware** [comment]
@yusukebe and @monoald might be worth another review. I didn't notice that the `newState` was being used in the CSRF checks. I adjusted this to make sure the passed state or the getRandomState is used, the previous change resulted in a 401 response if you passed state

**Comment by yusukebe** [comment]
@aaronware Thank you!

It looks good to me. But I want @melbourne2991 to review it, too.

**Comment by monoald** [comment]
@yusukebe Sorry for not testing it properly the first time. I have tested it locally now, and it works fine. It successfully authenticates

**Comment by yusukebe** [comment]
@aaronware @monoald 

Okay! Merging now. Thanks for your contribution!!

**Pull request merged**
