### PR TITLE
feat(trpc): access hono context from trpc procedures

### PR DESCRIPTION
**Pull request by benjamine**
this would solve #455

change should be backwards compatible (so not bumping the minor version).

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @benjamine 

Look good! One thing: can you run `yarn changeset` on the top level of the project to create a changeset? I think it will be a `minor` change (not patch or major), because it provide a new feature.

**Comment by benjamine** [comment]
@yusukebe sorry for the delay, just added the minor changeset

**Comment by yusukebe** [comment]
@benjamine 

Thank you very much! I'll merge this and release it now.

**Comment by benjamine** [comment]
you're welcome, thank you for hono! 🙏

**Pull request merged**
