### PR TITLE
feat(swagger-uri): Add Full Configuration Parameters and Update Dependencies

### PR DESCRIPTION
**Pull request by naporin0624**
This PR introduces new rendering options for Swagger UI, enhancing configurability and updating dependencies for improved compatibility.

## Changes:
1. **Dependency Update:**
   - Update `@types/swagger-ui-dist` to `^3.30.5`.

2. **New Rendering Options:**
   - Add options such as `queryConfigEnabled`, `displayOperationId`, `tagsSorter`, `useUnsafeMarkdown`, `onComplete`, `syntaxHighlight`, `tryItOutEnabled`, `requestSnippets`, `oauth2RedirectUrl`, `showMutableRequest`, `request`, `supportedSubmitMethods`, `validatorUrl`, `withCredentials`, `modelPropertyMacro`, `parameterMacro`.

3. **Renderer and Test Updates:**
   - Apply rendering types and add test cases for each new option.
   - Fix type errors in test cases and refactor tests using `it.each` for better readability and maintenance.

ref: https://github.com/orgs/honojs/discussions/3077#discussioncomment-9938364

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @naporin0624 thank you for the PR! Looks good to me.

@Luizfelz @AlphaLawlessv Can you review this?

**Comment by Luizfelz** [comment]
Hi, @yusukebe . I just replied the review I did with @AlphaLawless  [here](https://github.com/orgs/honojs/discussions/3077#discussioncomment-9972059).

**Comment by naporin0624** [comment]
@Luizfelz

Thank you for the review.

The property that accepts the function that has already been implemented is implemented as a string, so we are going to match it to a string.
This is how it was intended to be used.
https://github.com/honojs/middleware/blob/main/packages/swagger-ui/test/option-renderer.test.ts#L101

I didn't know that `tagsSorter` accepts `alpha` and Function. I don't support the `string | Function` structure at this stage, so I'll think of another way.

**Comment by naporin0624** [comment]
Hi, @Luizfelz The following changes have been made.
As it is difficult to handle unions with `tagsSorter`, and we decided that if we could handle functions, we could handle alphas as well, so we tried to handle it by adding comments.

In addition, we decided that it would be difficult to receive functions as strings, so we added annotations using jsdoc.
https://github.com/honojs/middleware/pull/618/commits/9978bc036b7e05e9c2985a3577d2efacf4ac3343


- added
  - `requestSnippetsEnabled` https://github.com/honojs/middleware/pull/618/commits/b160e65aa45438bd7f1559fdd22985924580f533


- fixed
  - `syntaxHighlight: true` types https://github.com/honojs/middleware/pull/618/commits/0196d21cd63fbde85b94f6fe71afca61a95983e7
  - `showMutabledRequest` keys https://github.com/honojs/middleware/pull/618/commits/26785db25a4f9a27dfcdc9c1311eadda5eabf3db

- removed
  - `useUnsafeMarkdown` https://github.com/honojs/middleware/pull/618/commits/adff2e3af31031c35dce6aaa31318368e9f3e187

**Comment by naporin0624** [comment]
Hi, @Luizfelz Thank you for testing it!
@yusukebe I'd like to release this with these changes.

**Comment by yusukebe** [comment]
@naporin0624 Awesome work! @Luizfelz Thank you for reviewing!

I'll merge this and release it now.

**Pull request merged**
